"""empty message

Revision ID: 870de17cd9dc
Revises: f82bf537da51
Create Date: 2024-03-14 02:09:51.526475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870de17cd9dc'
down_revision = 'f82bf537da51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
