"""empty message

Revision ID: 95e384f9b529
Revises: 37c6b2c4ac37
Create Date: 2024-03-15 00:27:10.798689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e384f9b529'
down_revision = '37c6b2c4ac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('endDate')
        batch_op.drop_column('startDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startDate', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
